-- SCHEMA CREATION --
CREATE SCHEMA puzzledb;

-- TABLE CREATION --
CREATE TABLE puzzledb.statuses (
    id INTEGER generated by default as identity PRIMARY KEY,
    status VARCHAR(200)
);

CREATE TABLE puzzledb.channels (
    id INTEGER generated by default as identity PRIMARY KEY,
    channelid BIGINT,
    channeltype VARCHAR(30),
    serverid BIGINT,
    notes VARCHAR(128)
);

-- SELECT * FROM puzzledb.channels;

CREATE TABLE puzzledb.puzzlehunts (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    huntname VARCHAR(128),
    theme VARCHAR(128),
    starttime TIMESTAMP,
    endtime TIMESTAMP
);

-- SELECT * FROM puzzledb.puzzlehunts;

CREATE TABLE puzzledb.puzzlehunt_puzzles (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    puzzleid VARCHAR(6),
    name VARCHAR(30),
    description VARCHAR(500),
    relatedlink VARCHAR(128),
    points INTEGER,
    requiredpoints INTEGER,
    answer VARCHAR(30),
    unlockoverride BOOLEAN
);

CREATE TABLE puzzledb.puzzlehunt_puzzle_partials (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    puzzleid VARCHAR(6),
    partialanswer VARCHAR(30),
    response VARCHAR(128)
);

CREATE TABLE puzzledb.puzzlehunt_text_strings (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    textkey VARCHAR(30),
    textstring VARCHAR(500)
);

CREATE TABLE puzzledb.puzzlehunt_solves (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    teamid INTEGER,
    solvetime TIMESTAMP,
    puzzleid VARCHAR(6)
);

CREATE TABLE puzzledb.puzzlehunt_solvers (
    uid INTEGER generated by default as identity PRIMARY KEY,
    id BIGINT,
    teamid INTEGER,
    huntid VARCHAR(30)
);

CREATE TABLE puzzledb.puzzlehunt_teams (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    teamname VARCHAR(30),
    teamchannel BIGINT,
    teamvoicechannel BIGINT,
    hintcount INTEGER
);

CREATE TABLE puzzledb.puzzlehunt_attempts (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    teamid INTEGER,
    solvetime TIMESTAMP,
    puzzleid VARCHAR(6),
    attempt VARCHAR(200)
);

CREATE TABLE puzzledb.puzzlehunt_faq (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    question VARCHAR (200),
    content VARCHAR(2000)
);

CREATE TABLE puzzledb.puzzlehunt_errata (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    puzzleid VARCHAR(6),
    content VARCHAR(2000)
);

CREATE TABLE puzzledb.puzzlehunt_team_applications (
    id INTEGER generated by default as identity PRIMARY KEY,
    huntid VARCHAR(30),
    teamid INTEGER,
    solverid BIGINT,
    recruited BOOLEAN,
    joined BOOLEAN
);

-- DATA POPULATION --
INSERT INTO puzzledb.puzzlehunt_text_strings (huntid, textkey, textstring) VALUES 
    ('system', 'Register Clarification', 'Please use this format: `hunt join <team name>`.'),
    ('system', 'Answer Clarification', 'Please use this format: `hunt solve <puzzleid> <answer phrase>` (puzzleid is case sensitive).'),
    ('system', 'Recruit Clarification', 'Please use this format: `hunt recruit \<@your team member>` and explicitly mention the person.'),
    ('system', 'No Hunt Running', 'There is no Puzzle Hunt running right now!'),
    ('system', 'Team Exists', 'This team exists. If you''re joining, ask someone in the team to perform `hunt recruit <@your account>` to complete this action.'),
    ('system', 'Adding Recruit', 'You are recruiting a member to your team. They will have to perform `hunt join <your team name>` to complete this action.'),
    ('system', 'Team Name Length', 'Your team name is too long! Please use a phrase under 30 characters.'),
    ('system', 'Team Name Format', 'Your team name cannot be accepted! Please use at least one alphanumeric character.'),
    ('system', 'Created Team', 'Team created successfully.'),
    ('system', 'Not in a Team', 'You cannot perform this command because you are not in a team. You should start by using `hunt join <team name>`'),
    ('system', 'Already in a Team', 'You cannot perform this command because you are already in a team. If you wish to change team, use `hunt leave`.'),
    ('system', 'Waiting for Recruitee', 'You have recruited a new member to your team. To confirm, ask said member to perform `hunt join <your team name>`.'),
    ('system', 'Recruitee in Team', 'Your recruitee is already in a team. They need to perform `hunt leave` first to join your team.'),
    ('system', 'Correct Answer', 'Your answer is... CORRECT! You have gained {puzzlepoints} points!'),
    ('system', 'Wrong Answer', 'Sorry, that is not the right answer.'),
    ('system', 'Wrong Channel', 'You cannot perform this action in the current channel. Please use your team channel.'),
    ('system', 'Already Solved', 'This puzzle has already been solved!'),
    ('system', 'Attempting Too Soon', 'You are attempting this puzzle again too soon! Please wait another {remainingtime} seconds.'),
    ('system', 'Hunt Not Started', 'You cannot perform this action since the hunt has not officially started.'),
    ('system', 'Missing Variable', 'Database variable missing: "{variablename}". Please contact admin.'),
    ('system', 'No Hints Available', 'You don''t have any hint requests available!'),
    ('system', 'Hint Instruction', 'Ask for hint: `hunt requesthint [details of your hint request]`. You currently have {numhints} hints available.'),
    ('system', 'Hint Too Short', 'Your hint request is too short. Please type at least 30 characters!'),
    ('system', 'You Gave Hints', 'You gave {numhints} hint(s) to `{teamname}`!'),
    ('system', 'Puzzle ID Not Available', 'The requested puzzle ID is not available!');
-- END POPULATION --

-- EXAMPLES --

-- To insert
--
-- INSERT INTO puzzledb.puzzlehunts (huntid, puzzlecount, huntname, theme, past) VALUES ('magical-arcade-machine', 0, 'Magical Arcade Machine', 'Retro Video Games', TRUE);
-- INSERT INTO puzzledb.puzzlehunts (huntid, puzzlecount, huntname, theme, past) VALUES ('avatar', 5, 'Avatar: The Last Puzzlehunt', 'The Last Airbender', FALSE);
-- INSERT INTO puzzledb.puzzlehunt_puzzles (huntid, puzzleid, name, relatedlink, points, requiredpoints) VALUES ('arcade', 'A1', 'Duck Hunt', 'https://google.com', 10,  0);

-- To update
--
-- UPDATE puzzledb.puzzlehunts SET huntid = 'arcade' where huntid = 'magical-arcade-machine';

-- To alter
--
-- ALTER TABLE exampletablename ADD COLUMN columnname VARCHAR(30);
-- ALTER TABLE exampletablename DROP COLUMN columnname;
-- ALTER TABLE exampletablename ALTER COLUMN columnname TYPE VARCHAR(30);